### ISSUE TITLE
跨日工時判斷問題

### ISSUE THREAD

**Issue by chuck-lee** [g0v/tw-shift-schedule#2]
使用工作時段：
D PM 8:00 ~ D+1 AM 12:00
D+1 AM 12:30 ~ D+1 AM 4:30
D+1 AM 5:00 ~ D+1 8:00

三個工作時段應該被合併計算；或後兩段工時被視為一日，判定與第一段工時的休息間隔過短。
但判斷圖示沒有顯示後兩段工時的狀態：
![workinghour](https://user-images.githubusercontent.com/880639/35219762-ce6f73ca-ffae-11e7-8352-d0bdfa4ce6cd.png)

**Comment by poga** [comment]
這個狀況中，[tw-shift-schedule](https://github.com/g0v/tw-shift-schedule) 有正確將三個工作時段合併計算，不過前端 UI 在顯示跨日時有 bug 所以顯示錯誤。

**Comment by poga** [comment]
介面已修正

![2018-01-24 09 27 47](https://user-images.githubusercontent.com/8631/35309776-0375937a-00e9-11e8-8b91-edebb726bb92.png)
